/*
 * Regenerates src/data/home.ts from the design's home page.
 *
 * Everything home.ts holds lives in the design as JS arrays (CASES, SYMPTOMS,
 * STEPS, RECEIPTS, LOGOS), so they are evaluated rather than scraped. Two
 * fields the design doesn't carry are reattached here: the featured cases'
 * `slug` (kept as a positional ORDER list, which throws if the count changes)
 * and `category`, which is read from PROJECTS in src/data/site.ts by slug.
 *
 * Hero copy, section headings and other one-off prose on the home page live
 * in src/pages/index.astro, not here — scripts/check-copy.mjs is what catches
 * drift in those.
 *
 * Usage: node scripts/gen-home.mjs "<path to Monzones-D-Paper.dc.html>"
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { readDesign, evalArray, smart, q, siteField } from './lib/design.mjs';

const source = process.argv[2];
if (!source) {
  console.error('Usage: node scripts/gen-home.mjs <Monzones-D-Paper.dc.html>');
  process.exit(1);
}

const html = readDesign(source);
const CASES = evalArray(html, 'CASES');
const SYMPTOMS = evalArray(html, 'SYMPTOMS');
const STEPS = evalArray(html, 'STEPS');
const RECEIPTS = evalArray(html, 'RECEIPTS');

// LOGOS is written as a name list piped through .map() — take just the names.
const logosStart = html.indexOf('const LOGOS = [');
const logosEnd = html.indexOf(']', logosStart);
// eslint-disable-next-line no-new-func
const LOGOS = new Function(`return [${html.slice(logosStart + 'const LOGOS = ['.length, logosEnd)}]`)();

/**
 * Slugs for the featured cases, in the design's order. The design identifies
 * them only by position, so a reordered or swapped lineup must be reflected
 * here deliberately rather than guessed at.
 */
const ORDER = ['mogo-lifecycle', 'winback', 'sportserve-payments-division', 'lead-enrichment'];
if (CASES.length !== ORDER.length) {
  throw new Error(
    `The design has ${CASES.length} featured cases but ORDER lists ${ORDER.length}. ` +
      'Update ORDER in scripts/gen-home.mjs to say which slug each position is.',
  );
}

const site = readFileSync(resolve('src/data/site.ts'), 'utf8').replace(/\r\n/g, '\n');

const lines = [];
const w = (s = '') => lines.push(s);
/** `key: 'value',` on one line if it fits, else wrapped under the key. */
const kv = (indent, key, value, width = 100) => {
  const one = `${indent}${key}: ${q(value)},`;
  if (one.length <= width) w(one);
  else {
    w(`${indent}${key}:`);
    w(`${indent}  ${q(value)},`);
  }
};

w('/**');
w(' * Home page content.');
w(' *');
w(" * These are the home page's own framings — the same projects told as \"here's");
w(' * where it started / here\'s what we learned" rather than as full case studies.');
w(' * Wording comes from the approved copy deck; the numbers agree with ./cases.ts');
w(' * because they describe the same work.');
w(' *');
w(' * Generated by scripts/gen-home.mjs from the design export. Edit the design');
w(' * file and re-run rather than hand-editing the prose here.');
w(' */');
w('');
w("import type { Category } from './site';");
w('');
w('/** The flip card under the hero: what someone asked for vs. what we found. */');
w('export const SYMPTOMS = [');
for (const s of SYMPTOMS) {
  w('  {');
  kv('    ', 'ask', smart(s.s));
  kv('    ', 'found', smart(s.c));
  w('  },');
}
w('] as const;');
w('');
w('export interface FeaturedCase {');
w('  /** Matches a slug in PROJECTS, so the card can link to the full case. */');
w('  slug: string;');
w('  client: string;');
w('  title: string;');
w('  category: Category;');
w('  /** Tab one — where the work started. */');
w('  brief: readonly string[];');
w('  /** Tab two — what the work turned out to be. */');
w('  read: readonly string[];');
w('  metric: string;');
w('  note: string;');
w('}');
w('');
w('/** The four cases shown in the shelf / grid switcher. */');
w('export const FEATURED_CASES: readonly FeaturedCase[] = [');
ORDER.forEach((slug, i) => {
  const c = CASES[i];
  w('  {');
  w(`    slug: ${q(slug)},`);
  kv('    ', 'client', smart(c.client));
  kv('    ', 'title', smart(c.title));
  w(`    category: ${q(siteField(site, slug, 'category'))},`);
  w('    brief: [');
  for (const p of c.brief) w(`      ${q(smart(p))},`);
  w('    ],');
  w('    read: [');
  for (const p of c.read) w(`      ${q(smart(p))},`);
  w('    ],');
  kv('    ', 'metric', smart(c.metric));
  kv('    ', 'note', smart(c.note));
  w('  },');
});
w('];');
w('');
w('/**');
w(' * The five-step method, each illustrated with what that step actually looked');
w(' * like on one project rather than described in the abstract.');
w(' */');
w('export const METHOD = [');
for (const s of STEPS) {
  w('  {');
  kv('    ', 'name', smart(s.name));
  kv('    ', 'source', smart(s.source));
  kv('    ', 'example', smart(s.example));
  w('  },');
}
w('] as const;');
w('');
w('export interface Receipt {');
w('  name: string;');
w('  /** Headline figure shown opposite the chart. */');
w('  headline: string;');
w('  window: string;');
w('  read: string;');
w('  /** Before/after bars. Omitted for figures that exist only as a delta. */');
w('  bars?: { before: number; after: number; beforeLabel: string; afterLabel: string };');
w('  /** Caption for a relative-only figure rendered as a single stat. */');
w('  single?: string;');
w('}');
w('');
w('/**');
w(' * The numbers section. A figure that exists without a baseline gets `single`');
w(' * rather than `bars`, because a before/after chart would invent a comparison');
w(" * that isn't in the data.");
w(' */');
w('export const RECEIPTS: readonly Receipt[] = [');
for (const r of RECEIPTS) {
  w('  {');
  kv('    ', 'name', smart(r.name));
  kv('    ', 'headline', smart(r.head));
  if (r.single) kv('    ', 'single', smart(r.sub));
  kv('    ', 'window', smart(r.win));
  if (!r.single) {
    w(
      `    bars: { before: ${r.before}, after: ${r.after}, beforeLabel: ${q(smart(r.bl))}, afterLabel: ${q(smart(r.al))} },`,
    );
  }
  kv('    ', 'read', smart(r.read));
  w('  },');
}
w('];');
w('');
w('/**');
w(' * Companies whose logos run in the marquee. The name maps to a file in');
w(' * src/assets/logos/ — see LogoMarquee.astro, which resolves them at build time');
w(' * so a missing file fails the build instead of shipping a broken image.');
w(' */');
w('export const LOGOS = [');
for (const name of LOGOS) w(`  ${q(name)},`);
w('] as const;');
w('');

const out = resolve('src/data/home.ts');
writeFileSync(out, lines.join('\n'), 'utf8');
console.log(
  `Wrote ${out}: ${SYMPTOMS.length} symptoms, ${CASES.length} featured cases, ` +
    `${STEPS.length} method steps, ${RECEIPTS.length} receipts, ${LOGOS.length} logos.`,
);
