/*
 * Regenerates src/data/cases.ts from the design export.
 *
 * The design file carries the case bodies as a plain JS array, so it is read
 * and evaluated rather than scraped — a regex over 30KB of prose would be a
 * worse bet than letting the parser do it. Existing key order in cases.ts is
 * preserved so the diff shows content changes and nothing else.
 *
 * Usage: node scripts/gen-cases.mjs "<path to Monzones-D-Case.dc.html>"
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const source = process.argv[2];
if (!source) {
  console.error('Usage: node scripts/gen-cases.mjs <Monzones-D-Case.dc.html>');
  process.exit(1);
}

const html = readFileSync(source, 'utf8').replace(/\r\n/g, '\n');

const start = html.indexOf('const CASES = [');
if (start === -1) throw new Error('Could not find `const CASES = [` in the design file.');
const end = html.indexOf('\n];', start);
if (end === -1) throw new Error('Could not find the end of the CASES array.');

const A = { coral: '#F2603F', sun: '#F5B841', sky: '#3E8FD8', moss: '#3FA981' };
const body = html.slice(start + 'const CASES = ['.length, end);
// eslint-disable-next-line no-new-func
const cases = new Function('A', `return [${body}]`)(A);

/** Order the file is written in — taken from the current cases.ts. */
const ORDER = [
  'mogo-lifecycle',
  'winback',
  'behavioral-trigger-layer',
  'esp-migration',
  'dafabet-sfmc',
  'agentic-ops',
  'lead-enrichment',
  'compliance-workflow',
  'mogo-web',
  'dtc-newsletter',
  'analytics-rebuild',
  'sportserve-payments-division',
  'craftconcepts',
];

const bySlug = new Map(cases.map((c) => [c.slug, c]));
const missing = ORDER.filter((s) => !bySlug.has(s));
const extra = cases.map((c) => c.slug).filter((s) => !ORDER.includes(s));
if (missing.length) throw new Error(`Missing from the design file: ${missing.join(', ')}`);
if (extra.length) throw new Error(`New slugs not in ORDER: ${extra.join(', ')}`);

/** Single-quoted TS string. The prose uses curly quotes, so only \ and ' need escaping. */
const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const lines = [];
const w = (s = '') => lines.push(s);

w('/**');
w(' * Long-form case study bodies, keyed by the same slug as `PROJECTS` in');
w(' * ./site.ts.');
w(' *');
w(' * The split is deliberate: site.ts owns what a project *is* — the card title,');
w(' * tags, category and headline metrics read by the home page and the work index.');
w(' * This file owns what the detail page adds on top, including its own `title`,');
w(' * because the full write-up wants a longer headline than a card can carry.');
w(' *');
w(' * Every case follows the same arc, because that is genuinely how the work went:');
w(' * the starting point → the decision → how I measured it → the build. Facts here');
w(' * come from Website MD Repository/Professional History and the approved copy');
w(" * deck. Do not invent a number, a date or a tool that isn't in those files.");
w(' *');
w(' * Generated by scripts/gen-cases.mjs from the design export. Edit the design');
w(' * file and re-run rather than hand-editing the prose here.');
w(' */');
w('');
w('export interface CaseSection {');
w('  label: string;');
w('  paras: readonly string[];');
w('}');
w('');
w('export interface CaseStat {');
w('  value: string;');
w('  label: string;');
w('}');
w('');
w('export interface CaseTech {');
w('  name: string;');
w('  use: string;');
w('}');
w('');
w('export interface CaseStudy {');
w('  /** Org · role · dates, exactly as recorded in Professional History. */');
w('  meta: string;');
w('  /** Headline for the detail page. */');
w('  title: string;');
w('  /** The one-line framing under the headline. */');
w('  deck: string;');
w('  sections: readonly CaseSection[];');
w('  stats: readonly CaseStat[];');
w('  /** The closing read — did the diagnosis hold? */');
w('  outcome: string;');
w('  tech: readonly CaseTech[];');
w('}');
w('');
w('export const CASES: Record<string, CaseStudy> = {');

for (const slug of ORDER) {
  const c = bySlug.get(slug);
  w(`  ${q(slug)}: {`);
  w(`    meta: ${q(c.meta)},`);
  w(`    title: ${q(c.title)},`);
  w(`    deck: ${q(c.deck)},`);
  w('    sections: [');
  for (const s of c.sections) {
    w('      {');
    w(`        label: ${q(s.label)},`);
    w('        paras: [');
    for (const p of s.paras) w(`          ${q(p)},`);
    w('        ],');
    w('      },');
  }
  w('    ],');
  w('    stats: [');
  for (const s of c.stats) w(`      { value: ${q(s.v)}, label: ${q(s.l)} },`);
  w('    ],');
  w(`    outcome: ${q(c.outcome)},`);
  w('    tech: [');
  for (const t of c.tech) w(`      { name: ${q(t.name)}, use: ${q(t.use)} },`);
  w('    ],');
  w('  },');
}

w('};');
w('');

const out = resolve('src/data/cases.ts');
writeFileSync(out, lines.join('\n'), 'utf8');

const paras = cases.reduce((n, c) => n + c.sections.reduce((m, s) => m + s.paras.length, 0), 0);
console.log(`Wrote ${out}: ${ORDER.length} cases, ${paras} paragraphs.`);
