/**
 * About page content.
 *
 * Prose lives here rather than in the template so the page file stays a layout
 * and the wording stays reviewable in one place. Dates are taken from
 * Website MD Repository/Professional History — they're checkable against
 * LinkedIn, so they're never approximated.
 *
 * Generated by scripts/gen-about.mjs from the design export. Edit the design
 * file and re-run rather than hand-editing the prose here.
 */

export const INTRO = [
  'Hey—thanks for taking the time to read this.',
  'I’m Miguel. I work across lifecycle, GTM, and automation—the connected systems that help someone move from a first click to becoming a long-term customer. I’ve spent eleven years doing that across fintech, SaaS, ecommerce, and a few industries I never expected to find myself in.',
  'I’m curious by default and a builder by upbringing. I like understanding how things work, listening to the people closest to a problem, and leaving behind something useful that can keep working without me.',
] as const;

export const WHAT_I_DO = [
  'Most of my work begins with a question. A customer journey isn’t working as expected, an important number has started moving in the wrong direction, or a team is spending too much energy holding a process together. I look across the experience, data, tools, and handoffs between people to understand what’s getting in the way.',
  'From there, I help teams decide what needs to change and build the system around it. Sometimes that means rebuilding a lifecycle journey. Sometimes it means fixing the experience after the click, connecting tools that should have been talking to each other, or automating work that no longer needs to be manual.',
  'I’ve spent most of my career doing this from inside companies, working alongside the people who know the customers and operations best. Right now, I’m consulting on lifecycle, conversion, and automation, and I’m open to the right senior role. Either way, if you’re working through something complicated, I’m always happy to hear about it.',
] as const;

/** The pull quote above the three scope examples. */
export const SCOPE_QUOTE = 'I tend to follow the problem wherever it goes.';

export const SCOPE_INTRO =
  'My job descriptions have rarely stayed fixed for long. Not because I’m trying to collect responsibilities, but because useful work often crosses the lines between teams, tools, and disciplines.';

export const SCOPE_PROOF = [
  'At Mogo, I joined to turn lifecycle into a more connected growth system. Following the customer journey led into web, analytics, martech, and eventually the automation infrastructure supporting teams across the business.',
  'At DTC Newsletter, I started as an email coordinator. As the company grew, so did the work: website operations, deliverability, martech, lifecycle strategy, and AI-powered lead workflows across DTC, Pilothouse, and its client accounts.',
  'At Sportserve, I began as an assistant to the department director. Over seven years, I learned the business from the inside, helped connect work across eight departments and twelve markets, and eventually built and led the Payments Operations division.',
] as const;

/**
 * Career totals. `countTo` opts a figure into the count-up animation — only
 * plain integers qualify, since "1.5M+" can't be counted to sensibly.
 */
export const TOTALS = [
  {
    value: '11+',
    label: 'Years building lifecycle and marketing systems',
    countTo: 11,
    suffix: '+',
  },
  { value: '14', label: 'Markets supported across several regions', countTo: 14 },
  { value: '1.5M+', label: 'Customers and subscribers reached' },
  { value: '100+', label: 'Projects brought from idea to launch', countTo: 100, suffix: '+' },
] as const;

/**
 * The beliefs list. Each entry is a claim and the reason it's held — the reason
 * is what stops it reading as a slogan. The last one carries the Adinkra name,
 * which is why its body is split around an italicised phrase.
 */
export const BELIEFS = [
  {
    claim: 'Understand before you build.',
    body:
      'I grew up on a farm, where problems rarely arrived with instructions and you learned to work with what you had. If something broke, the first job was understanding why. That taught me to observe carefully, ask questions, and make sure I’m solving the right problem before reaching for a solution.',
  },
  {
    claim: 'Numbers show you where to look. People help you understand why.',
    body:
      'A dashboard can show where customers are hesitating or leaving, but it can’t fully explain what they experienced in that moment. The useful answer usually comes from combining the data with curiosity, customer context, and the knowledge held by people closest to the work.',
  },
  {
    claim: 'If a system only works when I’m in the room, it isn’t finished.',
    body:
      'I document what I build, involve the people who will operate it, and make handoff part of the work—not an afterthought. I’ve trained a successor in every major role I’ve left. The real test is whether the system keeps helping people after I’m gone.',
  },
  {
    claim: 'Be honest about the tradeoffs.',
    body:
      'Every worthwhile decision gives something up somewhere else: time, cost, flexibility, speed, or simplicity. I’d rather make those tradeoffs visible early so everyone can make the decision with clear eyes.',
  },
  {
    claim: 'And one I keep on my wrist.',
    /** Split so the Adinkra name can be set in italics without markup in data. */
    body: {
      phrase: 'Nea Onnim No Sua A, Ohu',
      after:
        '—“He who does not know can know from learning.” It’s an Adinkra symbol and Akan proverb I have tattooed on my right wrist. I don’t really believe in “I can’t do this.” I believe in “I haven’t learned it yet.”',
    },
  },
] as const;

export const OUTSIDE_WORK = [
  'I travel for the food as much as the place. Given the choice between a famous viewpoint and somewhere the locals genuinely love to eat, I’ll usually take the second. Sharing a meal tells me something about people and their culture that I’d never learn from a checklist of landmarks.',
  'I’m also into comics, games, and adventure stories. I’ve read all of Tolkien and once wandered very far into Warhammer 40,000 lore for no practical reason whatsoever. I think it comes from the same place as travel: I enjoy being dropped into a world I don’t understand yet and slowly working out how everything fits together.',
  'There’s almost always jazz or Latin music playing while I work. Jazz for the soul and improvisation; Latin music because it’s difficult to sit still when it’s on. Joy matters to me, and I try to work in a way that leaves room for it.',
  'I live in Vancouver with my girlfriend, Alejandra, and our fat cat, Katy—with a K. We take Katy on adventures. She continues to register her objections.',
] as const;

export const TO_WORK_WITH = [
  'I’m curious, collaborative, and fairly open about what I’m thinking. I ask a lot of questions, share what I’m noticing, and make room for the people closest to the work to challenge my read. I care more about reaching the right answer together than being the person who arrived with it.',
  'I get genuinely invested in the problems I work on. Part of that is because they feel like puzzles, but the more important part is knowing the answer can make something easier for a customer or the team behind the experience. Eleven years in, I still enjoy the moment when the pieces begin to connect—and turning that understanding into something useful.',
] as const;

/**
 * Job titles here are the ones that appear on LinkedIn, and the same strings
 * are used in the `meta` line of every case study in ./cases.ts. If one changes
 * it has to change in both places, or a recruiter reading a case page and a
 * recruiter reading this list see two different job titles.
 */
/**
 * The skills grid: eight groups, each with a one-line summary and the tools
 * behind it. Accents reuse the site's category tokens.
 */
export const SKILLS = [
  {
    name: 'Lifecycle marketing & CRM',
    accent: 'var(--coral)',
    skills:
      'Journey design, segmentation, activation, retention, reactivation, email/SMS/push strategy, deliverability governance, lead scoring.',
    tools: ['Braze', 'Salesforce Marketing Cloud', 'HubSpot', 'Marketo', 'Klaviyo', 'Iterable', 'Intercom', 'ActiveCampaign', 'Campaign Monitor', 'Mailchimp', 'Omnisend', 'SendGrid'],
  },
  {
    name: 'AI & automation',
    accent: 'var(--moss)',
    skills:
      'AI workflow design, enrichment pipelines, intelligent routing, agent-based workflows, deterministic and generative hybrid design, validation and safeguards.',
    tools: ['n8n', 'Zapier', 'Make', 'LindyAI', 'Clay', 'OpenAI API', 'Claude', 'Gemini', 'Gumloop', 'Voiceflow'],
  },
  {
    name: 'Analytics & experimentation',
    accent: 'var(--sky)',
    skills:
      'Tracking architecture, tagging, attribution modelling, funnel diagnostics, experiment design, reporting.',
    tools: ['GA4', 'Google Tag Manager', 'Looker Studio', 'Amplitude', 'Mixpanel', 'Branch Metrics', 'Snowflake', 'BigQuery', 'VWO', 'Optimizely', 'Hotjar'],
  },
  {
    name: 'Web, UX & CRO',
    accent: 'var(--sun)',
    skills:
      'Web strategy, information architecture, conversion optimisation, landing-page and funnel systems, web ownership and governance.',
    tools: ['Webflow', 'WordPress', 'Shopify', 'Figma', 'Instapage', 'Unbounce', 'Squarespace', 'Mouseflow'],
  },
  {
    name: 'SEO, AEO & GEO',
    accent: 'var(--sky)',
    skills:
      'Technical SEO, schema markup, Core Web Vitals, answer- and generative-engine optimisation, entity and knowledge-graph work, internal linking.',
    tools: ['Semrush', 'Ahrefs', 'Moz', 'Google Search Console', 'SurferSEO', 'Schema.org', 'PageSpeed Insights'],
  },
  {
    name: 'Data & scripting',
    accent: 'var(--coral)',
    skills: 'SQL querying, data modelling basics, data hygiene, ETL logic, measurement frameworks.',
    tools: ['SQL', 'Snowflake', 'BigQuery', 'Python (pandas)', 'Segment', 'Hightouch', 'Airtable'],
  },
  {
    name: 'Marketing ops & delivery',
    accent: 'var(--moss)',
    skills:
      'PM systems, Agile/Scrum/Kanban, sprint planning, process design, cross-functional alignment, documentation governance, RACI models.',
    tools: ['ClickUp', 'Jira', 'Asana', 'Wrike', 'Monday.com', 'Notion', 'Confluence', 'Trello', 'Airtable'],
  },
  {
    name: 'Acquisition & creative',
    accent: 'var(--sun)',
    skills:
      'Campaign performance and UTM governance, content production oversight, copywriting, visual direction, template systems.',
    tools: ['Google Ads', 'Meta Business Suite', 'LinkedIn Ads', 'Canva', 'Figma', 'Photoshop', 'Illustrator', 'Hootsuite', 'Buffer', 'Sprout Social'],
  },
] as const;

export const ROLES = [
  {
    org: 'Mogo',
    title: 'Senior Marketing Operations Manager (Lifecycle and MarTech)',
    what: 'Lifecycle, martech, web, and AI automation across Mogo’s fintech products',
    years: '2024 — now',
  },
  {
    org: 'CraftConcepts',
    title: 'Founder and Growth Strategist',
    what:
      'Built a 20+ person collective that helped 26 small businesses rebuild their digital presence after the pandemic',
    years: '2022 — 2025',
  },
  {
    org: 'DTC Newsletter · Pilothouse',
    title: 'Email & Website Operations Manager (MarTech)',
    what:
      'Lifecycle, web, martech, deliverability, and AI workflows across two companies and client accounts',
    years: '2021 — 2024',
  },
  {
    org: 'Sportserve',
    title: 'Senior Marketing Projects and Operations Manager',
    what:
      'Global lifecycle and payments operations; built and led the Payments Operations division',
    years: '2014 — 2021',
  },
  {
    org: 'Rappler',
    title: 'Editor and Contributor',
    what: 'Editing and fact-checking in a 24/7 Manila newsroom, where I trained under Maria Ressa',
    years: '2013 — 2014',
  },
] as const;

/** The 20-second intro clip, linked rather than embedded to keep the page light. */
export const INTRO_VIDEO = {
  href: 'https://youtu.be/WegUH6EIXgY',
  label: '20 seconds of me talking',
} as const;
