/**
 * Long-form case study bodies, keyed by the same slug as `PROJECTS` in
 * ./site.ts.
 *
 * The split is deliberate: site.ts owns what a project *is* — the card title,
 * tags, category and headline metrics read by the home page and the work index.
 * This file owns what the detail page adds on top, including its own `title`,
 * because the full write-up wants a longer headline than a card can carry.
 *
 * Every case follows the same arc, because that is genuinely how the work went:
 * the starting point → the decision → how I measured it → the build. Facts here
 * come from Website MD Repository/Professional History and the approved copy
 * deck. Do not invent a number, a date or a tool that isn't in those files.
 *
 * Generated by scripts/gen-cases.mjs from the design export. Edit the design
 * file and re-run rather than hand-editing the prose here.
 */

export interface CaseSection {
  label: string;
  paras: readonly string[];
}

export interface CaseStat {
  value: string;
  label: string;
}

export interface CaseTech {
  name: string;
  use: string;
}

export interface CaseStudy {
  /** Org · role · dates, exactly as recorded in Professional History. */
  meta: string;
  /** Headline for the detail page. */
  title: string;
  /** The one-line framing under the headline. */
  deck: string;
  sections: readonly CaseSection[];
  stats: readonly CaseStat[];
  /** The closing read — did the diagnosis hold? */
  outcome: string;
  tech: readonly CaseTech[];
}

export const CASES: Record<string, CaseStudy> = {
  'mogo-lifecycle': {
    meta: 'Mogo · Senior Marketing Operations Manager (Lifecycle and MarTech) · 2024 – present',
    title: 'The Mogo lifecycle rebuild',
    deck: 'Activation was stuck, and lifecycle email was the natural first place to look. Following the customer path showed the web experience and the lifecycle running on separate tracks.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'Activation was hovering around 24%, so lifecycle email was the natural place to begin investigating.',
          'Engagement was healthy, though, which encouraged us to look at what customers experienced after the click. Following the product path, the web experience and the lifecycle program were running as two separate tracks: users were dropping off inside the product before the emails had a chance to land. The lifecycle was timed to a behaviour that wasn’t happening yet.',
          'That reframed the work. Activation wasn’t an email problem, it was a web and lifecycle alignment problem, and everything downstream followed from that.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Rebuild the lifecycle around the actual product activation event instead of a time-based email sequence. That meant rebuilding the web experience in parallel, instrumenting the real behavioural triggers, and treating lifecycle as an extension of the product rather than a marketing layer on top of it.',
          'It wasn’t a campaign brief. It was an architectural decision about how lifecycle and product relate to each other.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Activation rate — bank-connection rate, specifically. Not open rate and not click rate, since those were already healthy, which was the confusing part. If activation moved, the read was right.',
          'I tracked 7-day drop-off as the inverse. Both numbers had to move together, or the intervention was noise.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'Rebuilt the onboarding web experience, added behavioural event tracking for real product actions, and rebuilt the lifecycle in Braze around those events instead of time delays, with segmented journeys for activated and not-yet-activated users on distinct messaging and timing logic.',
          'Product and Engineering instrumented the activation event with me, and Data helped shape the measurement framework. The Braze rebuild took six weeks, and the numbers moved inside two months of launch.',
        ],
      },
    ],
    stats: [
      { value: '24% → 38%', label: 'Activation rate' },
      { value: '78% → 62%', label: '7-day drop-off' },
    ],
    outcome: 'Activation moved because the lifecycle was finally tracking real product behaviour, and drop-off fell because users who weren’t activating got a different experience rather than more email.',
    tech: [
      { name: 'Braze', use: 'Lifecycle and behavioural messaging' },
      { name: 'Webflow', use: 'Onboarding web experience' },
      { name: 'Segment', use: 'Event tracking and data routing' },
      { name: 'Looker', use: 'Measurement and reporting' },
    ],
  },
  'winback': {
    meta: 'Mogo · Senior Marketing Operations Manager (Lifecycle and MarTech) · 2024 – present',
    title: 'The Intelligent Investing winback and cross-sell',
    deck: 'About 900,000 people had either gone quiet on investing or never started. It was not one audience, and it was never going to be one campaign.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'Leadership wanted investing activations out of a dormant base of roughly 900,000 people. The first thing that mattered was that it wasn’t one audience: some had gone quiet on Intelligent Investing, but a large part of the pool were lending customers who had never invested with us at all, which is a cross-sell rather than a winback.',
          'The two products needed different pitches on top of that. Manage is automated weekly investing into an S&P 500 strategy. Self-directed is manual trading with research alongside it. One list, four different conversations.',
          'And I genuinely didn’t know what the list quality was. Pruning it on guesswork would have thrown away contacts that were still worth something, so that question had to be answered under real campaign conditions rather than assumed.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Build it as a multi-iteration program rather than a campaign. Iteration 1 would do two jobs at once: give a real read on conversion, and act as the list clean-up, since engagement under live conditions is the only honest signal of who is still reachable.',
          'Two behavioural hooks anchored the whole thing. For the Manage path, an investment calculator where someone could model what a small weekly contribution grows into by 75. For Self-directed, Fiscal.ai — a research tool already included in every Mogo membership, so the pitch was about something they already had.',
          'Messaging split by relationship rather than by segment name. Lending customers got progression: you have borrowed with us, here is how to start building. Dormant investors got resumption without judgment: you paused, and you are still an investor as far as we are concerned.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Conversion rate, with one condition attached: Iteration 1 was also the decision gate for how to treat the list afterwards — who to keep, who to cull, and what to do with the segment that never engaged at all.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'Iteration 1 ran February to June 2025 across the full pool. Re-introduction in month one with a subject-line resend to non-openers, product-specific tracks through months two and three, then objection handling in months three and four using a one-click survey where people named their own barrier — too risky, cash flow, confused about the products, or already investing somewhere else. Each answer got its own response: risk mapped to long-term dollar-cost-averaging education and the calculator, cash flow to micro-contribution framing at ten or twenty dollars a week, confusion to plain product explainers, and other platforms repositioned as complementary rather than competitive. Months four and five tapered off for the coldest segments.',
          'That round converted about 2.7%. Afterwards I culled hard bounces, spam complaints, and anything with three or more soft bounces, which brought the reachable audience to roughly 600,000.',
          'Iteration 2 ran July 2025 to January 2026 on the cleaned list and converted about 5% — around 30,000 people who either activated for the first time or came back to real activity. The structural call in that round was what to do with people who had never interacted at all. Going dark on them risks a reputation spike whenever you eventually return, and normal cadence just burns them, so I ran a low-frequency monthly drip instead: one educational email a month, alternating between calculator content and Fiscal.ai research concepts.',
        ],
      },
    ],
    stats: [
      { value: '~54K', label: 'Activated or returned across two rounds' },
      { value: '~2.7% → ~5%', label: 'Conversion, Iteration 1 to Iteration 2' },
      { value: '~900K', label: 'People in the original pool' },
    ],
    outcome: 'Iteration 3 is running now against the remaining ~300K, with a sunset program planned for whatever is left after it. The numbers matter less than what the program left behind: a repeatable winback and cross-sell architecture — the two-hook model, cleaning the list as you convert it, and the low-frequency drip for the coldest segments — plus proof that lending-to-investing cross-sell works when you frame it as progression and give it more than one pass.',
    tech: [
      { name: 'Braze', use: 'Segmentation, iteration waves and cross-channel delivery' },
      { name: 'Investment calculator', use: 'Behavioural hook for the Manage path' },
      { name: 'Fiscal.ai', use: 'Research hook for the Self-directed path' },
      { name: 'One-click survey', use: 'Objection capture and routing' },
    ],
  },
  'behavioral-trigger-layer': {
    meta: 'Mogo · Senior Marketing Operations Manager (Lifecycle and MarTech) · 2024 – present',
    title: 'Building the behavioural trigger layer',
    deck: 'Funded accounts weren’t turning into first trades, and the activation sequence was firing on a schedule rather than on what people had just done.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'Users were funding their accounts and stopping there, and the lifecycle had no path at all from a funded account to a first trade.',
          'The scheduled emails made the case for why to trade, which is the right message earlier in the journey. These users had already decided to fund — they were stuck on the next step, not the first one.',
          'Looking at the timing showed the underlying issue: the lifecycle was timed, not triggered. Someone who funded yesterday and someone who funded six weeks ago received the same email on the same day.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Rebuild the trigger layer around real product events. Funded-idle is a specific signal, and it needed its own journey, its own timing, and its own messaging logic, separate from the general activation sequence.',
          'Treat funded-idle as a distinct lifecycle stage rather than a variation of onboarding.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Funded-idle to first-trade conversion. Not activation broadly and not engagement, but the specific transition from funded and dormant to first real product action. That was the number that showed whether the trigger layer was working.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'Instrumented the funded-idle event in Braze as a behavioural trigger and built a dedicated journey that fired on account funding rather than on a schedule, with messaging built around the barrier a funded user actually faces: not why to trade, but how to place a first trade right now.',
          'Built separate branches for users who funded and did nothing, users who viewed the trading interface without executing, and users who started a trade and dropped off, each with its own logic and timing. Product confirmed the event instrumentation was clean before we scaled it.',
        ],
      },
    ],
    stats: [
      { value: '~19%', label: 'Funded-idle to first trade at two months, where there had been no path before' },
      { value: '~24%', label: 'The same rate on the longer-term read' },
    ],
    outcome: 'Responding to what users had just done, rather than how long they’d been in the funnel, was what moved revenue behaviour. It also made the case for the next step: branching the whole Canvas by product intent.',
    tech: [
      { name: 'Braze', use: 'Multi-channel Canvas architecture' },
      { name: 'Product event instrumentation', use: 'Behavioural triggers' },
      { name: 'Push deep-linking', use: 'Suppression and frequency logic' },
    ],
  },
  'esp-migration': {
    meta: 'DTC Newsletter · Email & Website Operations Manager (MarTech) · 2021 – 2024',
    title: 'ESP migration and deliverability rescue',
    deck: 'Sender score in the low 20s and inbox placement falling, with the cause sitting in the sending infrastructure rather than the content.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'Open rates were falling and spam placement was rising, so content was the reasonable first place to look — cleaner subject lines, tighter segmentation, fresher copy.',
          'The infrastructure told a different story. DTC was on a shared IP inside ActiveCampaign, and other senders on that IP were damaging a reputation we had no way to influence from our end. A dedicated IP would have solved it, but it wasn’t in the budget.',
          'So the deliverability problem wasn’t fixable within the platform we were on. The only real fix was a migration.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Move to Campaign Monitor, where we could get a clean sending environment, warm a new domain properly, and own our reputation from the ground up.',
          'That was more than an ESP swap. It meant migrating 200K+ subscribers, rebuilding every automation, reconfiguring authentication, and warming the new domain before a single campaign could go out. The newsletter ran 5× a week, with no pause button.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Sender score. Not open rate and not click rate, since both were already suppressed by the deliverability problem itself. The underlying reputation score was the leading indicator, and everything downstream would follow it.',
          'Secondary: spam placement rate via GlockApps. Inbox versus spam across the major providers gave us a real-time read on whether the migration was working.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'Built the migration in phases so the newsletter never stopped: DKIM, SPF, and DMARC configured on the new domain, a warming sequence executed from zero before scaling to full list volume, and every automation rebuilt from scratch.',
          'Segmented the list before the first send into active, inactive, and zero-engagement, started warming with the most engaged segment only, and expanded volume as sender score climbed. ZeroBounce cleaned the list, GlockApps monitored placement, and Litmus covered rendering. Then I wrote deliverability SOPs so the team had a defined response if scores slipped again.',
        ],
      },
    ],
    stats: [
      { value: '20s → 90+', label: 'Sender score' },
      { value: '200K+', label: 'Subscribers migrated' },
      { value: '5× / week', label: 'Send cadence maintained throughout' },
    ],
    outcome: 'The sender score recovered and then stabilized above 90 with the SOPs in place. The infrastructure had been the constraint all along, and once it was clean the content had a fair chance to perform.',
    tech: [
      { name: 'Campaign Monitor', use: 'Primary ESP post-migration' },
      { name: 'ZeroBounce', use: 'List hygiene and bounce management' },
      { name: 'GlockApps', use: 'Inbox placement monitoring' },
      { name: 'Litmus', use: 'Rendering and spam filter testing' },
      { name: 'DKIM / SPF / DMARC', use: 'Email authentication' },
    ],
  },
  'dafabet-sfmc': {
    meta: 'Sportserve (Dafabet) · Senior Marketing Projects and Operations Manager · 2014 – 2021',
    title: 'Salesforce lifecycle automation — Dafabet',
    deck: 'Twelve countries, safer-gambling compliance in every market, and no system connecting user behaviour to messaging.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'Dafabet had users, products, and markets across APAC, EU, and LATAM. What it didn’t have was a lifecycle system that responded to what users actually did.',
          'New users were registering without placing a first bet, existing users were going dormant with no triggered re-engagement, high-value users weren’t being identified or treated differently, and every message had to satisfy safer-gambling requirements that varied by jurisdiction.',
          'Put together, what existed were occasional batch campaigns with no behavioural logic connecting them. The product had a clear activation event — the first bet — and nothing was built around it.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Build six interconnected behavioural flows in Salesforce Marketing Cloud with the first bet as the central activation milestone, and design the compliance layer into the architecture from the start rather than as a review step at the end.',
          'The compliance-first choice changed how the team worked. When compliance lives in the architecture, campaigns ship faster; when it sits at the end, every send turns into another round of back-and-forth.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'First-bet conversion rate. In a gaming product the first bet is the activation event — retention, LTV, and cross-sport engagement all depend on whether the user crosses that threshold.',
          'Secondary: 7-day reactivation rate. If the re-engagement flows were working, that number would move independently of acquisition volume.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'Six flows, each triggered by a specific behavioural event. First-bet activation fired on registration with no bet inside 24 hours: email immediately, push at one hour, second email at 24 hours. Dormant re-engagement fired at 7+ days with no bet, pulling upcoming matches by geo and sport preference, then an AMPscript-driven promo respecting regional caps, then an in-play push or SMS.',
          'High-value nurturing identified power users at 3+ bets a week or top-20% average stake and routed them to account managers. A first-withdrawal trust flow fired off a withdrawal event pushed in via API. Churn-risk signals triggered jurisdiction-approved responsible gambling copy. A sport-usage matrix flagged single-sport bettors for cross-sport expansion.',
          'AMPscript handled regional cap enforcement, jurisdiction-specific copy variants, and promo eligibility at the send level, so the compliance rules lived inside the architecture rather than waiting at the end of it.',
        ],
      },
    ],
    stats: [
      { value: '+8–15%', label: 'First-bet conversion rate' },
      { value: '+10–20%', label: '7-day dormant reactivation' },
      { value: '+20–40%', label: 'CTR on triggered vs. batch campaigns' },
    ],
    outcome: 'Six flows, one connected system, one activation milestone at the centre. It proved a principle I carried into every lifecycle system I built after: if the system doesn’t know what the user just did, it can’t send the right message.',
    tech: [
      { name: 'Salesforce Marketing Cloud', use: 'Lifecycle orchestration' },
      { name: 'Journey Builder', use: 'Flow design and execution' },
      { name: 'AMPscript', use: 'Dynamic content and compliance logic' },
      { name: 'Data Extensions', use: 'Behavioural segmentation' },
      { name: 'MobilePush / SMS Studio', use: 'Cross-channel delivery' },
    ],
  },
  'agentic-ops': {
    meta: 'Mogo · Senior Marketing Operations Manager (Lifecycle and MarTech) · 2024 – present',
    title: 'Agentic ops infrastructure',
    deck: 'Leadership wanted automation before a platform or an owner had been named, and what the Ops teams needed most was the ability to build things themselves.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'The direction was clear — we are automating — with no tool selected, no owner named, and no scope defined. Ops teams were working manually on loan routing, compliance review, and email production, and leadership wanted AI involved.',
          'Talking it through with the teams, the underlying need was less about AI than about the manual bottlenecks slowing everything down. They needed to do more without adding headcount. The tool was the vehicle, not the point.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'I took a hybrid architecture to the COO: Zapier for the messy integrations with existing systems, and self-hosted n8n on the AWS infrastructure we already had for the high-volume operational work. Zapier per-task pricing breaks at operational scale, so self-hosting kept both the cost and the ownership internal as volume grew.',
          'The other half of the decision was who it was for. This had to be infrastructure the Ops teams could build on themselves, not a service a central team ran for them, or I would only be moving the dependency from Engineering onto me.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Underwriter close rate on the applications the system routed. It was the most direct measure of whether the automation was freeing up the right capacity for the right work, and if it did not move, the infrastructure was not earning its place.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'DevOps handled the infrastructure setup; I owned the operational use cases, the workflow architecture and the rollout. The first production build was loan application profiling and routing. Loan Ops were sorting and prioritising applications by hand, and that sorting was where the delay actually sat, so I sat with them to learn how they were making those calls, mapped the criteria into scoring logic, and automated the routing into the right queues.',
          'From there I went looking for the next use cases rather than waiting to be asked, and the infrastructure grew to more than fifteen production automations. Then I wrote the documentation, put the SOPs in Confluence, and ran sessions with each Ops lead so their team could build and maintain their own.',
        ],
      },
    ],
    stats: [
      { value: '~30%', label: 'Underwriter close rate on the applications the system routed' },
      { value: '15+', label: 'Automations in production, run by the Ops teams themselves' },
    ],
    outcome: 'Underwriters spent less time sorting and more time closing, which is where the close rate came from. The part that mattered more was what the starting read pointed at: Ops teams now build and extend their own workflows, so what began as one automation project became a capability the business owns without me.',
    tech: [
      { name: 'n8n', use: 'Self-hosted on existing AWS for high-volume workflows' },
      { name: 'Zapier', use: 'Integrations with existing systems' },
      { name: 'OpenAI API', use: 'Application profiling and scoring logic' },
      { name: 'Confluence', use: 'SOPs, documentation and training material' },
    ],
  },
  'lead-enrichment': {
    meta: 'DTC Newsletter / Pilothouse · Email & Website Operations Manager (MarTech) · 2021–2024',
    title: 'AI-powered lead enrichment and routing',
    deck: 'A request to enrich newsletter signups became a system that gave Sales useful context while a prospective customer’s interest was still fresh.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'DTC Newsletter signups were reaching the shared Pilothouse HubSpot instance with basic contact information but little company context, qualification data, or indication of which leads deserved immediate attention.',
          'The CFO wanted to enrich those records automatically. Before building anything, I spoke with the stakeholders involved to understand what information would actually help Sales. Enrichment was useful, but it wasn’t the end goal. The larger need was faster qualification and real-time visibility when someone from a promising company signed up.',
          'The opportunity was to turn each signup into a structured, sales-ready record and surface the strongest leads while their interest was still fresh.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'I designed the workflow around speed-to-contact rather than enrichment volume. That changed what the system needed to produce: not simply more data, but a reliable record that helped Sales understand who had signed up, where they worked, how well they fit, and whether the lead warranted immediate attention.',
          'The system needed to filter, research, classify, validate, populate the CRM, and alert the right people in one connected flow.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Lead-data pre-population rate was the clearest measure of whether the record was genuinely useful. By the time Sales opened a new lead, most of the research and qualification context should already be there.',
          'I also tracked the number of signups processed and enriched leads produced each month to make sure the workflow remained useful at real operating volume — not only in testing.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'I began by defining what a sales-ready HubSpot record needed to contain, then mapped the research, classification, validation, and routing steps required to produce it.',
          'LindyAI orchestrated the workflow, detected new signups, and filtered out generic email domains. StoreLeads supplied company-level data, while LinkedIn and web sources supported contact research. Clay was added in a later iteration to improve the depth and accuracy of company and contact enrichment. The ChatGPT API assessed company fit and persona, and returned the information in a defined structure before the validated record was written to HubSpot. When a high-value lead appeared, Slack alerted Sales and leadership in real time.',
          'The workflow went through several iterations. Early versions produced inconsistent classifications on edge cases, so I tightened the prompts, required structured outputs, and added validation before anything could populate the CRM. Once the system was reliable, we adapted the same workflow pattern for other Pilothouse B2B client accounts.',
        ],
      },
    ],
    stats: [
      { value: '~70%', label: 'Of lead data populated before Sales touched the record' },
      { value: '~300', label: 'Newsletter signups processed each day' },
      { value: '1K–2K', label: 'Enriched, sales-ready leads generated each month' },
    ],
    outcome: 'The workflow gave Sales and leadership real-time visibility into high-value signups while reducing the manual research needed before outreach. More importantly, it turned enrichment into a dependable part of the revenue workflow: useful context arrived in HubSpot in a consistent format, unreliable AI output was stopped before reaching the CRM, and the system could handle real daily volume.',
    tech: [
      { name: 'LindyAI', use: 'Primary workflow orchestration, triggering, filtering, and enrichment coordination' },
      { name: 'StoreLeads + Clay', use: 'Company and contact enrichment, with Clay added in a later iteration to improve depth and accuracy' },
      { name: 'LinkedIn + web data', use: 'Sources used for contact and company research' },
      { name: 'ChatGPT API', use: 'Company-fit assessment, persona classification, and structured AI output' },
      { name: 'HubSpot', use: 'CRM destination and structured lead-record population' },
      { name: 'Slack', use: 'Real-time routing and alerts for high-value leads' },
    ],
  },
  'compliance-workflow': {
    meta: 'Mogo · Senior Marketing Operations Manager (Lifecycle and MarTech) · 2024 – present',
    title: 'Email validation and compliance workflow',
    deck: 'The first validation workflow ran fine technically and still nobody leaned on it, because it wasn’t checking what Compliance actually reviews.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'Every lifecycle email went through four to five rounds of review between the lifecycle team and Compliance before it could send. With no self-serve QA, each send became a back-and-forth that added days to production.',
          'The original request was a spam checker, something to flag obvious deliverability risks before content reached Compliance. I built that first version. It worked technically, but the output was inconsistent.',
          'The reason became clear once I put it next to the review itself: the workflow was checking spam signals, while Compliance was reviewing for specific regulatory language, prohibited claims, and jurisdiction-specific disclosure rules. I had designed it without the people who do that reviewing.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Stop iterating on the technical layer and redesign the workflow outward from the compliance review process, with Compliance as a design partner rather than a downstream approver.',
          'Rebuilding from scratch rather than patching the existing workflow cost time upfront, and it was the only route to something the team would genuinely rely on.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Compliance review cycles per email — how many rounds of back-and-forth before sign-off. That was the friction the workflow existed to remove, and if the number didn’t drop it wasn’t working, whatever it produced technically.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'I sat with Compliance before touching the workflow and documented how they actually reviewed content: what they looked for, what triggered a flag, what the rules were per content category, what varied by jurisdiction. That logic became the prompt architecture and validation layer.',
          'It took four versions. V1 checked spam signals — functional, but aimed at the wrong question. V2 added compliance flag categories: better output, still inconsistent, because the model was interpreting rules rather than applying them. V3 brought Compliance in and replaced interpretation with explicit rule sets — reliable, but too verbose to use. V4 restructured the output so results were actionable in seconds.',
          'Built in n8n so the lifecycle team could run validation themselves while drafting. Compliance reviews the output rather than the email, so the compliance question is answered before the email reaches them.',
        ],
      },
    ],
    stats: [
      { value: '4–5 → 1–2', label: 'Compliance review cycles per email' },
      { value: '~50%', label: 'Fewer compliance review cycles' },
      { value: '4', label: 'Versions to get it right' },
    ],
    outcome: 'What I took from it was less about the tool than about who you design with. The first three versions fell short because I was building a compliance workflow without a compliance expert alongside me. Subject matter experts aren’t approvers. They’re design inputs.',
    tech: [
      { name: 'n8n', use: 'Workflow orchestration and self-serve QA' },
      { name: 'OpenAI API', use: 'Content validation and flag classification' },
      { name: 'Braze', use: 'Lifecycle email production pipeline' },
      { name: 'Confluence', use: 'Workflow documentation and rule sets' },
    ],
  },
  'mogo-web': {
    meta: 'Mogo · Senior Marketing Operations Manager (Lifecycle and MarTech) · 2024 – present',
    title: 'Mogo web ecosystem rebuild',
    deck: 'Marketing needed to ship pages in hours while the website sat with DevOps, and that ownership question turned out to be central rather than incidental.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'Lifecycle conversion was weak, and email was the reasonable first suspect. Looking upstream, the emails were performing reasonably; what wasn’t performing was where they sent people. Campaign traffic landed on generic product pages with little relation to the message someone had just read.',
          'The second issue was structural. The website was owned by DevOps, so any change needed an engineering ticket and a campaign landing page took weeks. Marketing had no way to move at campaign speed.',
          'Two problems at once, then: a conversion problem from lifecycle-web misalignment, and an ownership problem from the tool sitting with the wrong team for the job.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Rebuild the web ecosystem in Webflow and move ownership to Marketing, with a component system that let any team member launch a page without engineering involvement, and lifecycle alignment and conversion intent designed into every page from the start.',
          'Use the migration as the forcing function to fix the tracking layer at the same time. GA4 and GTM carried years of undocumented tag debt, and rebuilding the site without fixing tracking would only have made the same attribution problem faster.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Conversion rate from lifecycle traffic — the specific failure the rebuild was meant to address. If lifecycle emails sent people to pages that matched the message and the intent, that number would move.',
          'Secondary: time to launch for a new page. The ownership problem was only solved if Marketing could actually ship without waiting on engineering.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'Rebuilt five properties: MogoTrade first as the proof of the Webflow model, then Moka, Intelligent Investing, orion-digital.com, and mogo.ca.',
          'Built a component system rather than individual pages — reusable sections, governed naming, and a CMS structure that let anyone assemble a page from the library in hours. Defined URL structures, content models, and metadata templates before touching layouts, so SEO and tracking were built in rather than retrofitted.',
          'Applied SEO, AEO, and GEO across all five properties: schema markup, canonical structures, internal linking, metadata by page type. Rebuilt GA4 and GTM in parallel, bringing Analytics, DevOps, Product, and Legal into the tracking architecture during the migration rather than after. Every page launched with clean event tracking on day one.',
        ],
      },
    ],
    stats: [
      { value: '+15%', label: 'Conversion from lifecycle traffic' },
      { value: '+30%', label: 'Conversion on campaign-specific landing pages' },
      { value: '~5% → ~14%', label: 'MogoTrade organic traffic share, within 90 days' },
    ],
    outcome: 'The lifecycle conversion problem turned out to be a destination problem. Once the pages matched the message and Marketing owned the ability to change them, conversion followed — and the component system meant the fix held for every campaign after, not just one.',
    tech: [
      { name: 'Webflow', use: 'Full web ecosystem and component system' },
      { name: 'GA4 + GTM', use: 'Rebuilt tracking infrastructure' },
      { name: 'Braze', use: 'Lifecycle-to-web traffic coordination' },
      { name: 'Semrush / Ahrefs', use: 'SEO audit and organic performance' },
      { name: 'Schema.org', use: 'Structured data and AEO implementation' },
      { name: 'Branch Metrics', use: 'App deep-link attribution' },
    ],
  },
  'dtc-newsletter': {
    meta: 'DTC Newsletter · Email & Website Operations Manager (MarTech) · 2021 – 2024',
    title: 'DTC Newsletter web and SEO rebuild',
    deck: 'The newsletter had a 70% bounce rate. The right people were arriving; the site just wasn’t giving them a reason to stay.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'DTC Newsletter had strong email engagement and a growing subscriber base. The website told a different story: bounce rate at 70%, organic traffic underperforming relative to content volume, and low signup conversion from organic visitors who were, by definition, high intent.',
          'Looking at the site itself, the information architecture had grown by accretion — content added over time without taxonomy or hierarchy, and no clear path from a search result to a signup. It had been built as a content container, which it did well. It hadn’t been built as a conversion system.',
          'So the bounce rate wasn’t about audience quality. The right people were landing and leaving again, because the page gave them no reason to stay.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Rebuild the architecture from the information model outward: taxonomy first, then URL structure, then page hierarchy, then layouts. Treat the site as a conversion system where every page had a job — capture a subscriber, build credibility with a sponsor, or rank for a term that brought in the next reader.',
          'I ran all of it end to end. No separate web team, no design handoff, no engineering queue. Three full rebuilds over the tenure.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Bounce rate, as the clearest signal of whether the site was working for the reader who arrived. If the architecture and content hierarchy were right, it would fall.',
          'Secondary: organic newsletter signup rate. The site’s job was ultimately to turn organic readers into subscribers, and that number had to move or the rebuild hadn’t addressed the right problem.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'The first version shipped with a clean content taxonomy, consistent URL structure, schema markup across all content types, and metadata templates matched to search intent by page category.',
          'The second rebuild expanded the system for growing content volume: new page types for sponsor content, resource sections, and topic cluster hubs, with internal linking built around keyword groupings.',
          'The third rebuild was forced by an external contractor deleting the entire Webflow environment. I rebuilt the full site from memory and documentation — every component, CMS collection, automation, and content system — without data loss. Operations never stopped.',
        ],
      },
    ],
    stats: [
      { value: '70% → 38%', label: 'Bounce rate' },
      { value: '+28%', label: 'Organic traffic' },
      { value: '+27%', label: 'Organic newsletter signups' },
    ],
    outcome: 'Three rebuilds taught the same lesson each time. Bounce rate was a symptom, and the real question was whether the page gave the reader a reason to be there. When the architecture matched how readers actually moved through the content, the numbers followed.',
    tech: [
      { name: 'Webflow', use: 'Full site development and CMS' },
      { name: 'Semrush / Ahrefs', use: 'SEO audit and keyword research' },
      { name: 'Google Search Console', use: 'Indexation and ranking data' },
      { name: 'Schema.org', use: 'Structured data implementation' },
      { name: 'GA4', use: 'Traffic and conversion tracking' },
      { name: 'Campaign Monitor', use: 'Newsletter signup integration' },
    ],
  },
  'analytics-rebuild': {
    meta: 'Mogo · Senior Marketing Operations Manager (Lifecycle and MarTech) · 2024 – present',
    title: 'Analytics and tracking infrastructure rebuild',
    deck: 'Leadership had stopped trusting the numbers, and the cause sat underneath the campaigns: years of undocumented tag debt.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'Performance reports were going out with a caveat that the numbers might not be accurate. The data had been unreliable long enough that leadership had stopped making decisions with it.',
          'GA4 was partially configured, and GTM held years of tags added without documentation, naming conventions, or governance. Attribution across web, app, and lifecycle was inconsistent, and nobody had a complete picture of what was firing, what was double-counting, and what wasn’t firing at all.',
          'The martech stack had grown tool by tool without a central owner. Braze, Intercom, and Microsoft Dynamics were running as silos — Braze wasn’t connected to Dynamics at all, so behavioural segmentation was blind to customer status, loan history, and account events.',
          'Two problems compounding each other, then: a broken tracking layer making reporting unreliable, and a disconnected stack holding lifecycle strategy back from what it could do.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Use the Webflow ecosystem rebuild as the forcing function to fix the tracking layer at the same time. That was what made the work possible without a separate project cycle — every page launching in Webflow could launch with clean tagging from day one instead of a retrofit afterward.',
          'Run the martech audit in parallel: map every tool, integration, and data flow, and surface what was missing, what was underused, and what was costing money without delivering value.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Data accuracy rate. The question leadership needed answered was whether they could trust what the reports showed, and accuracy at the event level was the only thing that answered it.',
          'Secondary: cost savings from the martech audit. Unused tools and redundant subscriptions surfacing from the diagnostic work were a direct business outcome.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'Created a new GA4 property from scratch with a full event taxonomy supporting lifecycle, acquisition, and retention measurement simultaneously — standardized naming, custom dimensions, and conversion event configuration.',
          'Rebuilt GTM completely in parallel with the Webflow migration, clearing years of tag debt and consolidating pixel management for Meta, LinkedIn, and other channels under GTM governance. Brought Analytics, DevOps, Product, and Legal into the process during the migration rather than after. Integrated Branch Metrics for mobile attribution, which had been essentially unmeasured.',
          'Ran the martech audit across the full stack, mapping data flows between Braze, Intercom, Dynamics, and supporting tools. Surfaced the Braze–Dynamics integration gap, escalated it to the COO, and got it onto the product roadmap. Identified about $18K in annual savings from unused features and redundant subscriptions, and delivered a tech roadmap for future scaling.',
        ],
      },
    ],
    stats: [
      { value: '40% → 80%', label: 'Data accuracy rate' },
      { value: '~$18K', label: 'Annual martech savings identified' },
    ],
    outcome: 'The rebuild didn’t improve campaign performance directly. It made campaign performance legible. When leadership can trust the data they make decisions with it, and when they can’t they stop looking at it entirely. The real outcome wasn’t better numbers — it was numbers that could be used.',
    tech: [
      { name: 'GA4', use: 'Analytics property rebuilt from scratch' },
      { name: 'Google Tag Manager', use: 'Full implementation and governance' },
      { name: 'Branch Metrics', use: 'Mobile attribution and deep-link tracking' },
      { name: 'Microsoft Dynamics CRM', use: 'Martech audit and integration mapping' },
      { name: 'Braze', use: 'Lifecycle platform and integration assessment' },
      { name: 'Looker', use: 'Measurement and reporting' },
    ],
  },
  'sportserve-payments-division': {
    meta: 'Sportserve · Senior Marketing Projects and Operations Manager · Mar 2014 – Feb 2021',
    title: 'Building the Payments Operations Division',
    deck: 'Payment launches touched eight departments and no single function held them together. I made the case for a dedicated division and built it from scratch.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'Sportserve ran payment launches across 12 countries, and every launch touched Product, Engineering, Compliance, Creative, Customer Support, and external payment providers. Each team could see its own piece clearly; nobody had a view of the whole sequence.',
          'Launches kept slipping, and fixing them one at a time was a reasonable response, since each delay had its own specific cause. Looking across the portfolio, though, the same pattern kept repeating, which pointed at something structural: no system connected the people who had to work together to ship a launch.',
          'From inside any one department that was invisible. It simply looked like a slow launch.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Solving launches one at a time would have meant solving them forever. I made the case to leadership for a standalone Payments Operations Division, built from zero, rather than another workaround.',
          'I designed it as an internal agency model: one team owning project management, B2C campaign execution, B2B onboarding coordination, creative production, vendor management, and customer issue resolution for everything payments-related, across all 12 markets.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Launch throughput and production error rate across the whole portfolio, not any single launch. If the system was working, every launch would get faster and cleaner, not only the ones I was close to. That was the honest test of whether the constraint really was structural.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'I hired the initial team of 5 and defined the operating model: Agile sprint cycles, RACI models for ownership clarity, centralized project tracking, and a data-driven prioritization framework that sequenced launches by market impact rather than by who asked first.',
          'I wrote the SOPs, the QA processes, and the standardized launch templates so the team could execute consistently without me in every decision. Then I traveled to new regional offices to train local teams in person, since the model only worked if it held the same way in every market.',
          'The division sat inside the broader MSOps department, which grew from 5 to 36 over the same stretch as four other leads built out their own divisions in parallel. That wider growth wasn’t my build. The 5-person division was.',
        ],
      },
    ],
    stats: [
      { value: '0 → 5', label: 'Team built from zero' },
      { value: '2×', label: 'Campaign throughput' },
      { value: '~40%', label: 'Production errors reduced' },
    ],
    outcome: 'Throughput doubled, errors dropped about 40%, and payment method adoption improved 20–30% by market, because launches finally ran through one system instead of eight. The structure outlasted me.',
    tech: [
      { name: 'Jira', use: 'Sprint planning and backlog management' },
      { name: 'Agile and RACI', use: 'Delivery governance and ownership clarity' },
      { name: 'Confluence', use: 'SOPs and operational documentation' },
      { name: 'Creative production tooling', use: 'Merchant assets and campaign creative' },
    ],
  },
  'craftconcepts': {
    meta: 'CraftConcepts · Founder and Growth Strategist · May 2022 – Jan 2025',
    title: 'Founding and scaling CraftConcepts',
    deck: 'Local businesses lost their digital presence after the pandemic and couldn’t afford an agency to fix it. I built a collective to close that gap, and used it to mentor early-career marketers on real client work.',
    sections: [
      {
        label: 'The starting point',
        paras: [
          'I was running lifecycle and web systems full-time at DTC/Pilothouse, with employer permission to take on local SMB work alongside it, and I kept meeting the same situation. Owners had lost whatever digital presence they’d built before the pandemic, and standard agency pricing put real help out of reach.',
          'The gap wasn’t expertise, it was access. Nobody was building a structure that could deliver real strategy and execution at those budgets, and freelancing solo would only ever help one business at a time.',
        ],
      },
      {
        label: 'The decision',
        paras: [
          'Serving more than one client properly meant building a team rather than taking clients one by one. I founded CraftConcepts with two co-founders, one on sales and one on creative, with one rule that never moved: nothing went out the door without me reviewing the strategy first, whoever had built it.',
          'There was no capital to hire, so I built the team through referrals and treated every contributor relationship as mentorship rather than labor. People learned how to diagnose a client’s actual problem and build the system that fixed it, then left with real client work for their own portfolios.',
        ],
      },
      {
        label: 'How I measured it',
        paras: [
          'Number of businesses served, since that showed whether the model scaled past me personally. And organic visibility, since that showed the work held up after we shipped it, not just that we shipped something.',
        ],
      },
      {
        label: 'The build',
        paras: [
          'I built a commission-based compensation model scaled to each client’s budget, paired with volunteer effort from contributors who wanted the portfolio experience more than the pay. I ran founder interviews with every client to draw out their real positioning before any build started, then wrote repeatable website and content playbooks so nobody started from zero on a new engagement.',
          'The team grew from 3 co-founders to 8 within the first year, then to a rotating collective of 20+ at peak in year two, including early-career marketers in both Vancouver and the Philippines. No formal hierarchy, no full-time staff — just people rotating through real client work under my review.',
        ],
      },
    ],
    stats: [
      { value: '3 → 20+', label: 'Contributors at peak' },
      { value: '26', label: 'Businesses served' },
      { value: '~40%', label: 'Organic visibility lift' },
    ],
    outcome: 'The model scaled past what I could do alone, not through traditional hiring but because the mentorship structure meant contributors could genuinely execute client work rather than shadow it. I wound it down deliberately in January 2025, once the gap it was built for had closed.',
    tech: [
      { name: 'Webflow and WordPress', use: 'Client website builds' },
      { name: 'SEO and CRO', use: 'Visibility and conversion work' },
      { name: 'Content and brand playbooks', use: 'Repeatable founder-interview-to-launch process' },
    ],
  },
};
