/**
 * Consulting page content.
 *
 * The v9 design turned this page into a standalone service page — its own
 * palette, its own nav, its own voice — the sibling of /web-design/. The copy
 * here is that design’s copy verbatim; the numbers and the platform notes are
 * the same claims the rest of the site makes, just said more directly.
 *
 * Pastels are named rather than hex-repeated: the page paints stat tiles,
 * engagement chips and case cards from the same four, so a swatch change is a
 * one-line change here.
 *
 * Generated by scripts/gen-consulting.mjs from the design export. Edit the
 * design file and re-run rather than hand-editing the prose here.
 */

/** The page's four pastels — see .cn { --cn-* } in pages/consulting.astro. */
export const PASTELS = {
  butter: 'var(--cn-butter)',
  sage: 'var(--cn-sage)',
  peri: 'var(--cn-peri)',
  stone: 'var(--cn-stone)',
} as const;

export type PracticeKey = 'lifecycle' | 'web' | 'ai';

export interface Practice {
  key: PracticeKey;
  name: string;
  /** Pastel behind the illustration. */
  blob: string;
  /** The blob's own irregular radius — each card leans a different way. */
  blobShape: string;
  /** Bullet colour in the expanded "what’s included" list. */
  dot: string;
  blurb: string;
  detail: string;
  items: readonly string[];
  tools: string;
}

export const PRACTICES: readonly Practice[] = [
  {
    key: 'lifecycle',
    name: 'Lifecycle & retention',
    blob: PASTELS.butter,
    blobShape: '52% 48% 58% 42% / 48% 55% 45% 52%',
    dot: '#b9a63c',
    blurb:
      'People sign up, then drift. The usual fix — more emails on a schedule — just talks at them.',
    detail:
      'I build journeys that react to what customers actually do, not how many days it’s been — so more of them activate, stick, and come back. At Mogo, that shift took activation from 24% to 38% in two months.',
    items: [
      'Lifecycle and CRM audit',
      'Onboarding and activation journeys',
      'Retention and habit-building programs',
      'Winback and cross-sell strategy',
      'Segmentation and event architecture',
      'Deliverability and sending infrastructure',
    ],
    tools: 'Braze · Klaviyo · HubSpot · Salesforce Marketing Cloud · Iterable · Segment',
  },
  {
    key: 'web',
    name: 'Conversion & web',
    blob: PASTELS.peri,
    blobShape: '46% 54% 50% 50% / 55% 44% 56% 45%',
    dot: '#5a6bc0',
    blurb:
      'Your campaign made a promise. Then someone clicked — and the page told a different story.',
    detail:
      'I review the journey from first click to completed action and fix what sits between: the message, the page, the measurement, the handoffs. Then Marketing can keep improving it without filing a ticket.',
    items: [
      'Customer journey and conversion teardown',
      'Website rebuild and information architecture',
      'Landing-page and funnel systems',
      'Analytics and tracking implementation',
      'SEO and AI-search visibility',
      'Web ownership and governance',
    ],
    tools: 'Webflow · WordPress · GA4 · Google Tag Manager · Ahrefs · Hotjar',
  },
  {
    key: 'ai',
    name: 'AI & automation',
    blob: PASTELS.sage,
    blobShape: '55% 45% 44% 56% / 46% 52% 48% 54%',
    dot: '#5e8f4c',
    blurb: 'The repetitive work eating your team’s week? It’s automatable — safely.',
    detail:
      'I start with the workflow, not the tool. We find where work slows down and where judgement stays human, then I build the integrations, validation, and error handling that keep it reliable — documented so your team owns it.',
    items: [
      'Automation audit and opportunity roadmap',
      'Lead enrichment, scoring, and real-time routing',
      'CRM and lifecycle workflow integration',
      'AI-assisted content, QA, and compliance validation',
      'Structured outputs, safeguards, and error handling',
      'Team training, documentation, and handoff',
    ],
    tools: 'n8n · Zapier · LindyAI · Clay · HubSpot · OpenAI API',
  },
];

export interface Engagement {
  name: string;
  length: string;
  /** Pastel behind the length chip. */
  chip: string;
  body: string;
  leave: string;
}

export const ENGAGEMENTS: readonly Engagement[] = [
  {
    name: 'Teardown',
    length: '1 week',
    chip: PASTELS.butter,
    body:
      'One sharp question, one focused week. I dig into the journey, data, and systems behind it and hand you the findings in order of impact.',
    leave: 'A written assessment and your next three moves.',
  },
  {
    name: 'Full audit',
    length: '2–3 weeks',
    chip: PASTELS.sage,
    body:
      'The wide-angle version. Journey, data, triggers, tools, and how work actually moves between your teams — including talking to the people who run it, so the plan matches reality.',
    leave: 'A prioritised plan: owner, success measure, and next action for every item.',
  },
  {
    name: 'Build',
    length: '6–12 weeks',
    chip: PASTELS.peri,
    body:
      'We’ve agreed what needs to exist — now I build it alongside your team. Tested, documented, and handed over properly. Live isn’t done; owned is done.',
    leave: 'A working system your team understands, can measure, and can keep improving.',
  },
  {
    name: 'Advisory retainer',
    length: 'Monthly',
    chip: PASTELS.stone,
    body:
      'You have the hands; you want a second brain. I help set priorities, review work in flight, and pressure-test decisions before they get expensive.',
    leave: 'A strategic partner on call as decisions come up.',
  },
  {
    name: 'Fractional',
    length: '1–2 days a week',
    chip: PASTELS.butter,
    body:
      'I sit inside the team and own the function — roadmap, decisions, coordination — while you develop or hire the people who’ll keep it long term.',
    leave: 'The function runs properly while you find its permanent owner.',
  },
  {
    name: 'Something else',
    length: 'Depends',
    chip: PASTELS.sage,
    body:
      'An interim stretch while you hire, a second opinion on a plan, a one-off build, a weird one. Tell me what you need — if I’m not the right person, I’ll say so and point you somewhere better.',
    leave: 'An honest recommendation either way.',
  },
];

export const FIT_YES = [
  'A metric that matters is heading the wrong way, and nobody’s sure why yet.',
  'The problem crosses lifecycle, product, web, and data — and nobody owns the space between them.',
  'You want your assumptions tested, not validated.',
  'You’re in fintech, SaaS, or ecommerce, with enough customer signal to learn from.',
  'You want to own the system when I leave — not rent me forever.',
] as const;

export const FIT_NO = [
  'You need extra hands for a campaign plan that’s already locked.',
  'The solution is fixed, and evidence pointing elsewhere wouldn’t be welcome.',
  'You need a full agency running five workstreams in parallel. It’s just me — that’s the point.',
  'The product is too early to have real customer behaviour to learn from.',
  'The deadline doesn’t leave room to understand the problem. Fast, yes. Reckless, no.',
] as const;

export const START_STEPS = [
  {
    num: '1',
    name: 'Send a note',
    body:
      'Two paragraphs: what’s happening, which number you’re watching, what you’ve tried. That’s plenty.',
  },
  {
    num: '2',
    name: 'A 30-minute call',
    body:
      'Free, and useful either way. We talk through the problem and whether I’m the right person for it. If I’m not, I’ll say so and point you somewhere better.',
  },
  {
    num: '3',
    name: 'A fixed-fee proposal',
    body:
      'What I recommend, what you get, the exact cost, and how we’ll measure success. Nothing starts until you say go.',
  },
] as const;

/**
 * Three cases surfaced as proof, linked to the full write-ups. `client` is the
 * practice area rather than the company — the card leads with the kind of
 * problem, and the write-up behind it names the client.
 */
export const PROOF = [
  {
    slug: 'mogo-lifecycle',
    client: 'Lifecycle & retention',
    bg: PASTELS.butter,
    title: 'Rebuilding lifecycle',
    line:
      'Email looked healthy; the after-click experience told a different story. Lifecycle, web, product, and measurement became one connected journey.',
  },
  {
    slug: 'winback',
    client: 'Reactivation & cross-sell',
    bg: PASTELS.peri,
    title: 'The Intelligent Investing winback and cross-sell',
    line:
      'Around 900,000 people had gone quiet. Understanding who they actually were turned one broad blast into four conversations that landed.',
  },
  {
    slug: 'lead-enrichment',
    client: 'AI automation',
    bg: PASTELS.sage,
    title: 'AI-powered lead enrichment and routing',
    line:
      'A newsletter signup became a sales-ready HubSpot record — research, AI classification, validation, and routing, all before Sales touched it.',
  },
] as const;

/** The stack section: tool categories, then the platforms known deepest. */
export const SYSTEMS = [
  {
    name: 'Lifecycle & CRM',
    tools: ['Braze', 'Klaviyo', 'Salesforce Marketing Cloud', 'HubSpot', 'Iterable', 'Marketo', 'ActiveCampaign', 'Intercom', 'Campaign Monitor', 'Mailchimp', 'Omnisend', 'SendGrid', 'SurveyMonkey'],
  },
  {
    name: 'Automation & AI',
    tools: ['n8n', 'Zapier', 'Make', 'LindyAI', 'Clay', 'OpenAI API', 'Claude', 'Gemini', 'Gumloop', 'Voiceflow'],
  },
  {
    name: 'Analytics & experimentation',
    tools: ['GA4', 'Google Tag Manager', 'Looker Studio', 'Amplitude', 'Mixpanel', 'Branch Metrics', 'Snowflake', 'BigQuery', 'VWO', 'Optimizely', 'Hotjar'],
  },
  {
    name: 'Web & conversion',
    tools: ['Webflow', 'WordPress', 'Shopify', 'Figma', 'Instapage', 'Unbounce', 'Squarespace', 'Mouseflow'],
  },
  {
    name: 'Search & visibility',
    tools: ['Semrush', 'Ahrefs', 'Moz', 'Google Search Console', 'SurferSEO', 'Schema.org', 'PageSpeed Insights'],
  },
  {
    name: 'Data & delivery',
    tools: ['SQL', 'Snowflake', 'Python (pandas)', 'Segment', 'Hightouch', 'Airtable', 'ClickUp', 'Jira', 'Notion', 'Confluence'],
  },
] as const;

export const DEPTH = [
  {
    name: 'Braze',
    level: 'Expert',
    note:
      'Rebuilt Mogo’s lifecycle from calendar-based sends to behaviour-triggered journeys across email, push, and SMS. Modular component rebuild cut build time ~75%.',
  },
  {
    name: 'Salesforce Marketing Cloud',
    level: 'Expert',
    note:
      'Journey Builder, AMPscript, and Data Extensions. Built a six-flow lifecycle architecture across 12 markets with regulatory compliance written into the flow logic.',
  },
  {
    name: 'HubSpot',
    level: 'Expert',
    note:
      'Three years running it as a shared platform across two companies — Marketing Hub and CRM — including the AI enrichment pipeline that generated 1–2K sales-ready leads a month.',
  },
  {
    name: 'Marketo',
    level: 'Advanced',
    note:
      'Two years of B2B client consulting through Pilothouse: campaign and program setup, nurture architecture, and lead scoring for longer, multi-touch sales cycles.',
  },
  {
    name: 'n8n',
    level: 'Advanced',
    note:
      'Self-hosted on AWS with 15+ production automations, including AI loan-application routing and compliance validation for lifecycle content.',
  },
  {
    name: 'Zapier',
    level: 'Advanced',
    note:
      'Resident automation lead across two companies: integration architecture, conversion tracking, and the enrichment pipeline behind speed-to-contact.',
  },
  {
    name: 'Webflow',
    level: 'Expert',
    note:
      '40+ builds. Rebuilt five Mogo product sites and moved web ownership from DevOps to Marketing, so the team could ship without a ticket queue.',
  },
  {
    name: 'Other ESPs',
    level: 'Advanced',
    note:
      'Klaviyo, Campaign Monitor, ActiveCampaign, Omnisend, and SurveyMonkey — sender infrastructure, flows, and list operations built across client brands and a 200K-subscriber newsletter.',
  },
] as const;

/** The four headline numbers. Same claims the case write-ups carry. */
export const CONSULTING_NUMBERS = [
  {
    value: '24% → 38%',
    label: 'Activation, two months after the Mogo lifecycle rebuild',
    bg: PASTELS.butter,
  },
  {
    value: '35% → 23%',
    label: 'First-year churn after the retention journeys launched',
    bg: PASTELS.sage,
  },
  {
    value: '~54K',
    label: 'People activated or won back across two Intelligent Investing rounds',
    bg: PASTELS.peri,
  },
  {
    value: '~70%',
    label: 'Of lead data filled in before Sales ever touched the record',
    bg: PASTELS.stone,
  },
] as const;
