/**
 * Consulting page content.
 *
 * Engagements declare which practice areas they apply to. Rather than hiding
 * the ones that don't fit, the page dims them and says so — "not for this area"
 * is more useful to a prospective client than a shorter list.
 *
 * Generated by scripts/gen-consulting.mjs from the design export. Edit the
 * design file and re-run rather than hand-editing the prose here.
 */

export type PracticeKey = 'lifecycle' | 'web' | 'ai';

export interface Practice {
  key: PracticeKey;
  name: string;
  accent: string;
  blurb: string;
  detail: string;
  items: readonly string[];
  tools: string;
}

export const PRACTICES: readonly Practice[] = [
  {
    key: 'lifecycle',
    name: 'Lifecycle & retention',
    accent: 'var(--coral)',
    blurb:
      'Onboarding, activation, retention, and winback—designed around what customers actually do and what helps them keep moving.',
    detail:
      'Lifecycle works best when messaging, product, web, and customer behaviour are treated as one connected journey. I look across that full experience to understand where people are hesitating, dropping off, or losing confidence. Then I help your team build journeys that respond to meaningful actions—not simply the number of days that have passed.',
    items: [
      'Lifecycle and CRM audit',
      'Onboarding and activation journeys',
      'Retention and habit-building programs',
      'Winback and cross-sell strategy',
      'Segmentation and event architecture',
      'Deliverability and sending infrastructure',
    ],
    tools: 'Braze · Klaviyo · HubSpot · Salesforce Marketing Cloud · Iterable · Segment',
  },
  {
    key: 'web',
    name: 'Conversion & web',
    accent: 'var(--sky)',
    blurb:
      'Making sure the experience after the click supports the promise that brought someone there.',
    detail:
      'A strong campaign can only do so much if the next step feels disconnected, unclear, or difficult to trust. I review the journey from the first click through the completed action, looking at the message, page, tracking, and handoffs between teams. The goal is a web experience that supports the customer journey and gives Marketing room to keep improving it.',
    items: [
      'Customer journey and conversion teardown',
      'Website rebuild and information architecture',
      'Landing-page and funnel systems',
      'Analytics and tracking implementation',
      'SEO and AI-search visibility',
      'Web ownership and governance',
    ],
    tools: 'Webflow · WordPress · GA4 · Google Tag Manager · Ahrefs · Hotjar',
  },
  {
    key: 'ai',
    name: 'AI & automation',
    accent: 'var(--moss)',
    blurb:
      'Practical automation that removes repetitive work, improves decision-making, and remains reliable when your team takes it over.',
    detail:
      'I start with the workflow, not the AI tool. Together, we identify where work is slowing down, which decisions can be supported safely, and where human judgement still matters. I then design the integrations, AI steps, validation, and error handling needed to make the system dependable under real operating conditions—and document it so your team can own it.',
    items: [
      'Automation audit and opportunity roadmap',
      'Lead enrichment, scoring, and real-time routing',
      'CRM and lifecycle workflow integration',
      'AI-assisted content, QA, and compliance validation',
      'Structured outputs, safeguards, and error handling',
      'Team training, documentation, and handoff',
    ],
    tools: 'n8n · Zapier · LindyAI · Clay · HubSpot · OpenAI API',
  },
];

export interface Engagement {
  name: string;
  length: string;
  /** Practice areas this shape actually fits. */
  fits: readonly PracticeKey[];
  body: string;
  leave: string;
  /**
   * The catch-all at the end of the list. It fits everything by definition, so
   * it's styled as an invitation to write rather than as another priced shape.
   */
  other?: true;
}

export const ENGAGEMENTS: readonly Engagement[] = [
  {
    name: 'Teardown',
    length: '1 week',
    fits: ['lifecycle', 'web', 'ai'],
    body:
      'A focused look at one clearly defined question. I review the relevant journey, data, and systems, then bring the findings together in order of importance.',
    leave: 'A concise written assessment and a clear set of next steps.',
  },
  {
    name: 'Full audit',
    length: '2–3 weeks',
    fits: ['lifecycle', 'web', 'ai'],
    body:
      'A wider look across the customer journey, data, triggers, tools, and the way work moves between teams. I also speak with the people who operate the system so the recommendations reflect how the work happens in practice.',
    leave:
      'A prioritised plan with a recommended owner, success measure, and next action for each item.',
  },
  {
    name: 'Build',
    length: '6–12 weeks',
    fits: ['lifecycle', 'web', 'ai'],
    body:
      'I work alongside your team to build or rebuild the lifecycle journeys, website, or automation system we’ve agreed on. The work includes testing, documentation, and a proper handoff—not just getting it live.',
    leave: 'A working system your team understands, can measure, and can continue improving.',
  },
  {
    name: 'Advisory retainer',
    length: 'Monthly',
    fits: ['lifecycle', 'ai'],
    body:
      'Ongoing strategic support for a team that already has people to execute. I help with priorities, review plans and work in progress, and provide a second perspective when the path forward isn’t obvious.',
    leave: 'A consistent strategic partner your team can call on as decisions arise.',
  },
  {
    name: 'Fractional',
    length: '1–2 days a week',
    fits: ['lifecycle', 'ai'],
    body:
      'I work inside the team and take responsibility for the function: setting the roadmap, making decisions, coordinating the work, and helping build the internal capability to own it long term.',
    leave: 'Clear ownership of the function while you develop or hire the right permanent team.',
  },
  {
    name: 'Something else',
    length: 'Depends',
    fits: ['lifecycle', 'web', 'ai'],
    other: true,
    body:
      'A one-off build, an interim stretch while you hire, a second opinion on an existing plan, or something that doesn’t fit neatly into the options above. Tell me what you need, and I’ll let you know whether I can genuinely help.',
    leave: 'A clear and honest recommendation, whether or not that means working together.',
  },
];

export const FIT_YES = [
  'An important customer or business metric is moving in the wrong direction, and the reason isn’t yet clear.',
  'The problem crosses lifecycle, product, web, data, or engineering, but nobody currently owns the full journey between them.',
  'You want someone who will listen to the people closest to the work, test the assumptions, and give you a clear recommendation.',
  'You’re working in fintech, SaaS, ecommerce, or another business with enough customer activity and data to learn from.',
  'You want to leave the engagement with a system and plan your team can continue running—not a permanent dependency on me.',
] as const;

export const FIT_NO = [
  'You primarily need additional production support for a campaign plan that has already been decided.',
  'The scope and solution are already fixed, with little room to revisit the underlying problem if the evidence points somewhere else.',
  'You need a full-service agency or several specialists working in parallel. I’m an independent consultant and stay directly involved in the work myself.',
  'The product is still too early to provide meaningful customer behaviour, traffic, or performance data.',
  'The timeline doesn’t leave enough room to understand the problem properly. I can work quickly, but I won’t pretend a rushed answer is a reliable one.',
] as const;

export const START_STEPS = [
  {
    num: '01',
    name: 'Send me a note',
    body:
      'Tell me what’s happening, which result you’re watching, and what you’ve already tried. A couple of paragraphs is plenty to get us started.',
  },
  {
    num: '02',
    name: 'A 30-minute conversation',
    body:
      'We’ll talk through the problem, the context around it, and what kind of help would be useful. The goal is to understand whether I’m the right person for the work. If I’m not, I’ll be honest about that and point you in a more useful direction when I can.',
  },
  {
    num: '03',
    name: 'A written proposal',
    body:
      'If there’s a fit, I’ll send a clear scope covering what I recommend, what you’ll receive, the fixed cost, the timing, and how we’ll measure success. Nothing begins until you’ve reviewed and approved it.',
  },
] as const;

/** Three cases surfaced as proof on the dark band, linked to the full write-ups. */
export const PROOF = [
  {
    slug: 'mogo-lifecycle',
    client: 'Mogo',
    accent: 'var(--coral)',
    title: 'Rebuilding lifecycle',
    line:
      'Email engagement was healthy, but customers were meeting a different experience after the click. We brought lifecycle, web, product, and measurement into one connected journey.',
  },
  {
    slug: 'winback',
    client: 'Mogo',
    accent: 'var(--sun)',
    title: 'The Intelligent Investing winback and cross-sell',
    line:
      'Around 900,000 people had gone quiet or never started investing. Understanding the different audiences and products turned one broad campaign into four more relevant conversations.',
  },
  {
    slug: 'lead-enrichment',
    client: 'DTC Newsletter / Pilothouse',
    accent: 'var(--moss)',
    title: 'AI-powered lead enrichment and routing',
    line:
      'A newsletter signup became a sales-ready HubSpot record, with company research, AI classification, validation, and real-time routing working together behind it.',
  },
] as const;

/** Headline numbers on the consulting page's dark band. */
export const CONSULTING_NUMBERS = [
  { value: '24% → 38%', label: 'Activation within two months of the Mogo lifecycle rebuild' },
  { value: '35% → 23%', label: 'First-year churn after the longer-term retention journeys launched' },
  { value: '~54K', label: 'People activated or returned across two Intelligent Investing rounds' },
  { value: '~70%', label: 'Of lead data populated before Sales touched the record' },
] as const;

export const WORTH_KNOWING = [
  {
    accent: 'var(--coral)',
    text:
      'You’ll work directly with me from the first conversation through the final handoff. I’m an independent consultant—not an agency—and I stay close to both the thinking and the work.',
  },
  {
    accent: 'var(--moss)',
    text:
      'Based in Vancouver and working remotely across North America and Europe. My experience spans 14 markets.',
  },
] as const;
