/**
 * Home page content.
 *
 * These are the home page's own framings — the same projects told as "here's
 * where it started / here's what we learned" rather than as full case studies.
 * Wording comes from the approved copy deck; the numbers agree with ./cases.ts
 * because they describe the same work.
 *
 * Generated by scripts/gen-home.mjs from the design export. Edit the design
 * file and re-run rather than hand-editing the prose here.
 */

import type { Category } from './site';

/** The flip card under the hero: what someone asked for vs. what we found. */
export const SYMPTOMS = [
  {
    ask: '“Activation is stuck around 24%. The emails don’t seem to be moving it.”',
    found:
      'Email engagement was healthy, so we looked beyond the inbox. The emails were setting one expectation while the product delivered another, and the lifecycle was responding to elapsed time rather than customer actions. The opportunity was to bring web, product, and lifecycle into one connected journey.',
  },
  {
    ask: '“People are dropping off during their first week.”',
    found:
      'We were asking people to connect their bank account before we had properly explained security, custody, or how their money was protected. Once we understood it as a trust problem, not simply a UX problem, we knew which part of the experience needed to change.',
  },
  {
    ask: '“Open rates are falling. Could the subject lines be the problem?”',
    found:
      'Content was the natural first suspect. Deliverability testing showed that the shared sending infrastructure had damaged our sender reputation, so even good emails weren’t reliably reaching the inbox. We needed to fix the infrastructure before asking the content to do more.',
  },
  {
    ask: '“Leadership wants us using AI. Where should we start?”',
    found:
      'Before choosing a workflow, I spoke with the Ops teams about where work was slowing down. The biggest need wasn’t another AI tool. It was giving teams a reliable way to build and manage their own automations without having to wait on Engineering.',
  },
] as const;

export interface FeaturedCase {
  /** Matches a slug in PROJECTS, so the card can link to the full case. */
  slug: string;
  client: string;
  title: string;
  category: Category;
  /** Tab one — where the work started. */
  brief: readonly string[];
  /** Tab two — what the work turned out to be. */
  read: readonly string[];
  metric: string;
  note: string;
}

/** The four cases shown in the shelf / grid switcher. */
export const FEATURED_CASES: readonly FeaturedCase[] = [
  {
    slug: 'mogo-lifecycle',
    client: 'Mogo · Lifecycle',
    title: 'Rebuilding lifecycle',
    category: 'Lifecycle',
    brief: [
      'Activation was hovering around 24%, and our lifecycle emails weren’t translating into enough connected accounts.',
    ],
    read: [
      'Email engagement was healthy, which told us people were paying attention. The disconnect appeared after the click: the emails set one expectation, the product and web journey created another, and the lifecycle was responding to days elapsed rather than the actions customers took.',
      'Solving it meant working across more than email. I partnered with Product, Creative, and Analytics to rebuild the web experience and Braze journey together. We moved web ownership from DevOps to Marketing so the team could continue improving the experience, and rebuilt the triggers around actual customer behaviour.',
      'We chose activation and seven-day drop-off as our shared measures of whether the new journey was working.',
    ],
    metric: '24% → 38%',
    note: 'Activation; seven-day drop-off fell from 78% to 62%',
  },
  {
    slug: 'winback',
    client: 'Mogo · Intelligent Investing',
    title: 'The Intelligent Investing winback',
    category: 'Lifecycle',
    brief: [
      'Around 900,000 people had either gone quiet on investing or had a Mogo lending relationship but never started investing. We wanted to help more of them take, or retake, the first step.',
    ],
    read: [
      'This wasn’t one audience or one campaign. Dormant investors needed an easy way back, while lending customers were being introduced to investing for the first time. Manage and Self-directed also asked for different behaviours and gave people different reasons to care.',
      'I designed the work as a multi-round program with separate paths for each audience and product. Manage centred on building a manageable weekly habit, supported by an investment calculator. Self-directed centred on making informed decisions, with Fiscal.ai as the research tool.',
      'The first round also gave us an honest read on list quality. Instead of removing people based on assumptions, we learned from their actual behaviour, cleaned the list, and used those signals to make the second round more relevant.',
    ],
    metric: '~54K',
    note: 'People activated or returned across the first two rounds',
  },
  {
    slug: 'sportserve-payments-division',
    client: 'Sportserve · Payments Operations',
    title: 'Building the payments division',
    category: 'Leadership & Operations',
    brief: [
      'As Sportserve grew, the company began creating specialist teams for its most important operational areas. I was asked to take ownership of everything related to payments.',
    ],
    read: [
      'Payments touched eight departments, twelve markets, and a long list of providers and regulatory requirements. Every team naturally saw the part it owned. What was missing was a shared way to carry a launch from an idea all the way to the customer.',
      'I built that operating system with the teams involved: sprint cycles, clear ownership models, launch templates, compliance checkpoints, localisation workflows, and shared project tracking.',
      'As the volume of work grew, I hired and trained a five-person Payments Operations team to keep launches moving and give every stakeholder a clear path from request to release.',
    ],
    metric: '0 → 5',
    note: 'Person division; throughput doubled and errors fell by approximately 40%',
  },
  {
    slug: 'lead-enrichment',
    client: 'DTC Newsletter / Pilothouse · AI Automation',
    title: 'From newsletter signup to sales-ready lead',
    category: 'AI & Automation',
    brief: [
      'The CFO wanted to automatically enrich people who signed up for DTC Newsletter. At the time, signups were reaching HubSpot as raw contact records, leaving Sales to research and qualify each one manually.',
    ],
    read: [
      'I met with the stakeholders involved to understand what Sales actually needed from the workflow. Enriched data would help, but the larger opportunity was speed-to-contact: identifying a promising company and putting useful context in front of Sales while that person’s interest was still fresh.',
      'I designed a system that filtered generic email addresses, researched the company and individual, assessed fit, structured the information into a sales-ready HubSpot record, and alerted Sales and leadership in Slack when a high-value lead appeared.',
      'Getting it into production took several iterations. Early versions produced inconsistent classifications, so I added validation between the AI steps, tightened the output structure, and refined how edge cases were handled before anything reached the CRM.',
      'The result was a workflow that processed around 300 signups a day, pre-populated approximately 70% of lead data before Sales touched the record, and generated 1,000 to 2,000 enriched, sales-ready leads each month. Once it was reliable, we adapted the system for other Pilothouse B2B client accounts.',
    ],
    metric: '~70%',
    note:
      'Of lead data populated before Sales touched the record; 1K–2K sales-ready leads generated monthly',
  },
];

/**
 * The five-step method, each illustrated with what that step actually looked
 * like on one project rather than described in the abstract.
 */
export const METHOD = [
  {
    name: 'Listen',
    source: 'Mogo · The first three weeks',
    example:
      'I started by looking at the email data alongside the onboarding flow and web journey, while speaking with the teams closest to each part of the experience. Email engagement was healthy, so we knew people were paying attention. The question was what happened next.',
  },
  {
    name: 'Understand',
    source: 'Mogo · Connecting the journey',
    example:
      'The emails were setting one expectation while the web and product experience created another. At the same time, lifecycle messages were being triggered by days elapsed rather than what customers had done. We needed to treat the journey as one connected experience.',
  },
  {
    name: 'Measure',
    source: 'Mogo · Agreeing on success',
    example:
      'Open rate wouldn’t tell us whether the full journey was improving; it was already healthy. We chose activation and seven-day drop-off because they reflected whether more people were moving forward and staying engaged after signup.',
  },
  {
    name: 'Build',
    source: 'Mogo · Six weeks',
    example:
      'I worked with Product, Creative, and Analytics to rebuild the Braze lifecycle around customer actions while leading the Webflow rebuild alongside it. That allowed the message, experience, and measurement to evolve together.',
  },
  {
    name: 'Learn',
    source: 'Mogo · Two months later',
    example:
      'Activation increased from 24% to 38%, while seven-day drop-off fell from 78% to 62%. Just as importantly, the work gave us a more useful way to think about lifecycle: as a connected customer experience shaped by messaging, product, web, and data.',
  },
] as const;

export interface Receipt {
  name: string;
  /** Headline figure shown opposite the chart. */
  headline: string;
  window: string;
  read: string;
  /** Before/after bars. Omitted for figures that exist only as a delta. */
  bars?: { before: number; after: number; beforeLabel: string; afterLabel: string };
  /** Caption for a relative-only figure rendered as a single stat. */
  single?: string;
}

/**
 * The numbers section. A figure that exists without a baseline gets `single`
 * rather than `bars`, because a before/after chart would invent a comparison
 * that isn't in the data.
 */
export const RECEIPTS: readonly Receipt[] = [
  {
    name: 'Activation',
    headline: '24% → 38%',
    window: 'First 2 months, Mogo lifecycle rebuild',
    bars: { before: 24, after: 38, beforeLabel: '24%', afterLabel: '38%' },
    read:
      'The journey improved once lifecycle, web, and product began setting the same expectations. We also moved from calendar-based messages to triggers based on what customers did. Activation increased from 24% to 38%, while seven-day drop-off fell from 78% to 62% over the same period.',
  },
  {
    name: 'Retention',
    headline: '35% → 23%',
    window: 'First-year churn, after the longer-term flows went in',
    bars: { before: 35, after: 23, beforeLabel: '35% churn', afterLabel: '23% churn' },
    read:
      'This work focused on helping people build confidence in long-term investing. The journeys reinforced simple but important ideas: consistent contributions, compounding, staying invested through volatility, and the value of avoiding unnecessary fees. When people better understood the habit they were building, more of them continued it.',
  },
  {
    name: 'Reactivation',
    headline: '~54K activated',
    window: 'Two rounds, Feb 2025 – Jan 2026',
    bars: { before: 96, after: 6, beforeLabel: '~900K reached', afterLabel: '~54K activated' },
    read:
      'The first round helped us learn which contacts were still reachable, which barriers were keeping them from investing, and which product made sense for each audience. We used those signals to clean the list and make the second round more relevant. Conversion increased from approximately 2.7% in the first round to approximately 5% in the second.',
  },
  {
    name: 'Deliverability',
    headline: 'Low 20s → 90+',
    window: 'Sender score, ESP migration at DTC',
    bars: { before: 22, after: 92, beforeLabel: 'low 20s', afterLabel: '90+' },
    read:
      'Content was the natural place to begin investigating, but inbox testing pointed us toward the sending infrastructure. Moving away from a damaged shared-IP environment, properly authenticating the new setup, and rebuilding our list-management practices helped sender reputation recover from the low 20s to above 90.',
  },
  {
    name: 'Automation',
    headline: '~70%',
    single: 'of lead data populated before Sales touched the record',
    window: 'AI lead enrichment and routing · DTC Newsletter / Pilothouse',
    read:
      'DTC Newsletter signups were reaching HubSpot without enough context for Sales to know which ones deserved immediate attention. I worked with the stakeholders involved to define what a genuinely useful record should contain, then built a workflow that researched each company and contact, assessed fit, validated the AI output, and alerted Sales when a high-value lead appeared. The system processed around 300 signups a day and generated 1,000 to 2,000 enriched, sales-ready leads each month.',
  },
  {
    name: 'Review cycles',
    headline: '4–5 → 1–2',
    window: 'Content QA workflow, Mogo',
    bars: { before: 90, after: 30, beforeLabel: '4–5 rounds', afterLabel: '1–2 rounds' },
    read:
      'Compliance reviews relied heavily on knowledge held by individual reviewers, so the early versions of the workflow couldn’t capture all the nuance involved. I brought Compliance into the design process, documented how they evaluated content, and translated those criteria into the validation logic. That gave the Marketing team better guidance while drafting and reduced the typical review from four or five rounds to one or two.',
  },
];

/**
 * Companies whose logos run in the marquee. The name maps to a file in
 * src/assets/logos/ — see LogoMarquee.astro, which resolves them at build time
 * so a missing file fails the build instead of shipping a broken image.
 */
export const LOGOS = [
  'Mogo',
  'Sportserve',
  'Dafabet',
  'Rappler',
  'Pilothouse',
  'DTC Newsletter',
  'Carta Worldwide',
  'Axis',
  'Sunlife',
  'Intelligent Investing',
  'WheelWiz',
  'Hulkmeal',
  'Vintage Frames',
  'G&B Pro',
  'Upearance',
] as const;
